name: Deriv Price Bot
on:
  schedule:
    - cron: "0 * * * *"   # hourly, times are in UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 70
    concurrency:
      group: deriv-price-bot
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run hourly loop (posts every 10 min)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DERIV_API_TOKEN: ${{ secrets.DERIV_API_TOKEN }}
          DERIV_APP_ID: ${{ secrets.DERIV_APP_ID }}
          DERIV_SYMBOL: frxEURUSD
          INTERVAL_SECONDS: "600"       # 10 minutes
          RUN_FOR_MINUTES: "60"         # 6 posts per run
        run: python -u scheduler.py
