name: 1s Indices Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes (adjust as needed)
  workflow_dispatch:        # allows manual run from GitHub Actions tab

jobs:
  one-second-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websocket-client numpy matplotlib

      - name: Run 1s indices bot
        run: python main_1s.py
        env:
          DERIV_API_KEY: ${{ secrets.DERIV_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
